Changed tabs to spaces

diff --git a/.config/system-wide/etc/zsh/zshrc b/.config/system-wide/etc/zsh/zshrc
--- a/.config/system-wide/etc/zsh/zshrc
+++ b/.config/system-wide/etc/zsh/zshrc
@@ -29,9 +29,9 @@ key[Right]=${terminfo[kcuf1]}
 key[PageUp]=${terminfo[kpp]}
 key[PageDown]=${terminfo[knp]}
 if [[ -n ${terminfo[kent]} ]]; then
-	key[KeypadEnter]=${terminfo[kent]} # does not work in screen and tmux
+    key[KeypadEnter]=${terminfo[kent]} # does not work in screen and tmux
 else
-	key[KeypadEnter]="\eOM" # this is what xterm uses...
+    key[KeypadEnter]="\eOM" # this is what xterm uses...
 fi
 key[ShiftTab]=${terminfo[kcbt]}
 
@@ -52,17 +52,17 @@ key[ShiftTab]=${terminfo[kcbt]}
 # Finally, make sure the terminal is in application mode, when zle is
 # active. Only then are the values from $terminfo valid.
 if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
-	#function zle-line-init () {
-	function terminfo_zle-line-init () {
-		echoti smkx
-	}
-	#function zle-line-finish () {
-	function terminfo_zle-line-finish () {
-		echoti rmkx
-	}
-	#zle -N zle-line-init
-	#zle -N zle-line-finish
-	# Note: these are called later by the real zle-line-init and zle-line-finish widgets
+    #function zle-line-init () {
+    function terminfo_zle-line-init () {
+        echoti smkx
+    }
+    #function zle-line-finish () {
+    function terminfo_zle-line-finish () {
+        echoti rmkx
+    }
+    #zle -N zle-line-init
+    #zle -N zle-line-finish
+    # Note: these are called later by the real zle-line-init and zle-line-finish widgets
 fi
 
 # Ctrl+arrow keys, these do not seem to have a terminfo entry
@@ -120,15 +120,15 @@ bindkey -M vicmd 'v' edit-command-line
 # This was written entirely by Mikael Magnusson
 # Basically type '...' to get '../..' with successive .'s adding /..
 function rationalise-dot {
-	# keep variables that are generated by =~ local
-	local MATCH MBEGIN MEND match mbegin mend BASH_REMATCH
-	if [[ $LBUFFER =~ '(^|/| | |'$'\n''|\||;|&)\.\.$' ]]; then
-		LBUFFER+=/
-		zle self-insert
-		zle self-insert
-	else
-		zle self-insert
-	fi
+    # keep variables that are generated by =~ local
+    local MATCH MBEGIN MEND match mbegin mend BASH_REMATCH
+    if [[ $LBUFFER =~ '(^|/| | |'$'\n''|\||;|&)\.\.$' ]]; then
+        LBUFFER+=/
+        zle self-insert
+        zle self-insert
+    else
+        zle self-insert
+    fi
 }
 zle -N rationalise-dot
 # Note: do not bind this in other modes!
@@ -154,24 +154,24 @@ bindkey -M vicmd "^[s" zle-prepend-sudo
 
 # Set $TERM to support colours
 if [[ -n "${COLORTERM}" || -n "${VTE_VERSION}" ]]; then
-	case "$TERM" in
-		'xterm') TERM='xterm-256color' ;;
-		'screen') TERM='screen-256color' ;;
-	esac
-	export TERM
+    case "$TERM" in
+        'xterm') TERM='xterm-256color' ;;
+        'screen') TERM='screen-256color' ;;
+    esac
+    export TERM
 fi
 
 # set LS_COLORS, which is used by ls and some others to colourise file names
 if type dircolors > /dev/null ; then
-	if [[ -f "~/.dir_colors.$TERM" ]]; then
-		eval $(dircolors -b "~/.dir_colors.$TERM")
-	elif [[ -f "/etc/DIR_COLORS.$TERM" ]] ; then
-		eval $(dircolors -b "/etc/DIR_COLORS.$TERM")
-	elif [[ -f "~/.dir_colors" ]]; then
-		eval $(dircolors -b "~/.dir_colors")
-	elif [[ -f "/etc/DIR_COLORS" ]] ; then
-		eval $(dircolors -b "/etc/DIR_COLORS")
-	fi
+    if [[ -f "~/.dir_colors.$TERM" ]]; then
+        eval $(dircolors -b "~/.dir_colors.$TERM")
+    elif [[ -f "/etc/DIR_COLORS.$TERM" ]] ; then
+        eval $(dircolors -b "/etc/DIR_COLORS.$TERM")
+    elif [[ -f "~/.dir_colors" ]]; then
+        eval $(dircolors -b "~/.dir_colors")
+    elif [[ -f "/etc/DIR_COLORS" ]] ; then
+        eval $(dircolors -b "/etc/DIR_COLORS")
+    fi
 fi
 
 # support colours in less
@@ -204,23 +204,23 @@ setopt no_bang_hist # disable access to the history with !
 
 # the following function allows to exclude boring commands from the history
 zshaddhistory_ignore() {
-	# $1 is the command line
-	# return value means
-	# 0 - add to history
-	# 1 - do not add to history
-	# 2 - add to history but do not store in history file
-	# uses $HISTIGNORE, which should be an array of regexes
+    # $1 is the command line
+    # return value means
+    # 0 - add to history
+    # 1 - do not add to history
+    # 2 - add to history but do not store in history file
+    # uses $HISTIGNORE, which should be an array of regexes
 
-	# keep variables that are generated by =~ local
-	local MATCH MBEGIN MEND match mbegin mend BASH_REMATCH
-	# check if this is configured at all
-	[[ -z "${HISTIGNORE}" ]] && return 0
-	# try each regex in $HISTIGNORE until the first match
-	for regex in ${HISTIGNORE}; do
-		[[ "${1%%$'\n'}" =~ "$regex" ]] && return 2
-	done
-	# nothing matched
-	return 0
+    # keep variables that are generated by =~ local
+    local MATCH MBEGIN MEND match mbegin mend BASH_REMATCH
+    # check if this is configured at all
+    [[ -z "${HISTIGNORE}" ]] && return 0
+    # try each regex in $HISTIGNORE until the first match
+    for regex in ${HISTIGNORE}; do
+        [[ "${1%%$'\n'}" =~ "$regex" ]] && return 2
+    done
+    # nothing matched
+    return 0
 }
 add-zsh-hook zshaddhistory zshaddhistory_ignore
 
@@ -268,21 +268,21 @@ FORCE_RUN_VCS_INFO=1
 zmodload zsh/datetime
 
 precmd_vcs_info() {
-	# Run vcs_info and measure how long it takes.
-	local vcs_info_start vcs_info_finish
-	vcs_info_start=$EPOCHREALTIME
-	vcs_info
-	vcs_info_finish=$EPOCHREALTIME
-	# Update vcs_info_time with the measured time if this run was not
-	# aborted early by pre-get-data.
-	${vcs_info_timing} && vcs_info_time=$(( $vcs_info_finish - $vcs_info_start ))
-	unset vcs_info_timing
+    # Run vcs_info and measure how long it takes.
+    local vcs_info_start vcs_info_finish
+    vcs_info_start=$EPOCHREALTIME
+    vcs_info
+    vcs_info_finish=$EPOCHREALTIME
+    # Update vcs_info_time with the measured time if this run was not
+    # aborted early by pre-get-data.
+    ${vcs_info_timing} && vcs_info_time=$(( $vcs_info_finish - $vcs_info_start ))
+    unset vcs_info_timing
 }
 add-zsh-hook precmd precmd_vcs_info
 
 # Must run vcs_info when changing directories.
 chpwd_vcs_info() {
-	FORCE_RUN_VCS_INFO=1
+    FORCE_RUN_VCS_INFO=1
 }
 add-zsh-hook chpwd chpwd_vcs_info
 
@@ -295,96 +295,96 @@ zstyle ':vcs_info:*' check-for-changes true
 zstyle ':vcs_info:*+pre-get-data:*' hooks pre-get-data
 
 +vi-set-vcs-symbol() {
-	# return the symbol for the detected vcs
-	case "${hook_com[vcs_orig]}" in
-		#bzr
-		#cdv
-		#darcs
-		#fossil
-		#mtn
-		#p4
-		#svk
-		#tla
-		cvs)
-			hook_com[vcs]='$'
-			;;
-		git)
-			hook_com[vcs]='±'
-			;;
-		hg)
-			hook_com[vcs]='☿'
-			;;
-		svn)
-			hook_com[vcs]='⚡'
-			;;
-		# *)
-		# 	hook_com[vcs]="${hook_com[vcs]}|"
-		# 	;;
-	esac
+    # return the symbol for the detected vcs
+    case "${hook_com[vcs_orig]}" in
+        #bzr
+        #cdv
+        #darcs
+        #fossil
+        #mtn
+        #p4
+        #svk
+        #tla
+        cvs)
+            hook_com[vcs]='$'
+            ;;
+        git)
+            hook_com[vcs]='±'
+            ;;
+        hg)
+            hook_com[vcs]='☿'
+            ;;
+        svn)
+            hook_com[vcs]='⚡'
+            ;;
+        # *)
+        #   hook_com[vcs]="${hook_com[vcs]}|"
+        #   ;;
+    esac
 }
 
 +vi-set-misc() {
-	if [[ "${hook_com[vcs_orig]}" == git* ]] && whence git &>/dev/null; then
-		local ahead behind stashes gitstatus
+    if [[ "${hook_com[vcs_orig]}" == git* ]] && whence git &>/dev/null; then
+        local ahead behind stashes gitstatus
 
-		ahead=$(git rev-list ${hook_com[branch]}@{upstream}..HEAD 2>/dev/null | wc -l)
-		behind=$(git rev-list HEAD..${hook_com[branch]}@{upstream} 2>/dev/null | wc -l)
-		if [[ "${ahead}" -gt 0 && "${behind}" -gt 0 ]]; then
-			gitstatus='↕'
-		elif [[ "${ahead}" -gt 0 && "${behind}" -eq 0 ]]; then
-			gitstatus='↑'
-		elif [[ "${ahead}" -eq 0 && "${behind}" -gt 0 ]]; then
-			gitstatus='↓'
-		else
-			gitstatus=''
-		fi
-		stashes=$(git stash list 2>/dev/null | wc -l)
-		if [[ "${stashes}" -gt 0 ]]; then
-			gitstatus+='•'
-		fi
+        ahead=$(git rev-list ${hook_com[branch]}@{upstream}..HEAD 2>/dev/null | wc -l)
+        behind=$(git rev-list HEAD..${hook_com[branch]}@{upstream} 2>/dev/null | wc -l)
+        if [[ "${ahead}" -gt 0 && "${behind}" -gt 0 ]]; then
+            gitstatus='↕'
+        elif [[ "${ahead}" -gt 0 && "${behind}" -eq 0 ]]; then
+            gitstatus='↑'
+        elif [[ "${ahead}" -eq 0 && "${behind}" -gt 0 ]]; then
+            gitstatus='↓'
+        else
+            gitstatus=''
+        fi
+        stashes=$(git stash list 2>/dev/null | wc -l)
+        if [[ "${stashes}" -gt 0 ]]; then
+            gitstatus+='•'
+        fi
 
-		hook_com[misc]+=${gitstatus}
-	fi
+        hook_com[misc]+=${gitstatus}
+    fi
 }
 
 +vi-pre-get-data() {
-	# This variable is used to return the information whether timing should
-	# be measured or not. Default to true, change it to false later on if
-	# necessary.
-	vcs_info_timing=true
+    # This variable is used to return the information whether timing should
+    # be measured or not. Default to true, change it to false later on if
+    # necessary.
+    vcs_info_timing=true
 
-	# Only Git and Mercurial support and need caching. Abort if any other
-	# VCS is used.
-	[[ "$vcs" != git && "$vcs" != hg ]] && return
+    # Only Git and Mercurial support and need caching. Abort if any other
+    # VCS is used.
+    [[ "$vcs" != git && "$vcs" != hg ]] && return
 
-	# If the shell just started up or we changed directories (or for other
-	# custom reasons) we must run vcs_info.
-	if [[ -n $FORCE_RUN_VCS_INFO ]]; then
-		FORCE_RUN_VCS_INFO=
-		return
-	fi
+    # If the shell just started up or we changed directories (or for other
+    # custom reasons) we must run vcs_info.
+    if [[ -n $FORCE_RUN_VCS_INFO ]]; then
+        FORCE_RUN_VCS_INFO=
+        return
+    fi
 
-	# If we got to this point, running vcs_info was not forced, so now we
-	# default to running it only if it was fast the last time.
-	# This choice may be overridden later on.
-	# (ret=1 means run it, ret=0 means don't)
-	[[ "${vcs_info_time}" -lt "${VCS_INFO_THRESHOLD:-0.25}" ]]
-	ret=$?
+    # If we got to this point, running vcs_info was not forced, so now we
+    # default to running it only if it was fast the last time.
+    # This choice may be overridden later on.
+    # (ret=1 means run it, ret=0 means don't)
+    [[ "${vcs_info_time}" -lt "${VCS_INFO_THRESHOLD:-0.25}" ]]
+    ret=$?
 
-	# If a git/hg command was run then run vcs_info as the status might
-	# need to be updated.
-	case "$(fc -ln $(($HISTCMD-1)))" in
-		git*)
-			ret=0
-			;;
-		hg*)
-			ret=0
-			;;
-	esac
+    # If a git/hg command was run then run vcs_info as the status might
+    # need to be updated.
+    case "$(fc -ln $(($HISTCMD-1)))" in
+        git*)
+            ret=0
+            ;;
+        hg*)
+            ret=0
+            ;;
+    esac
 
-	if [[ ${ret} -ne 0 ]]; then
-		vcs_info_timing=false
-	fi
+    if [[ ${ret} -ne 0 ]]; then
+        vcs_info_timing=false
+    fi
 }
 
 # }}}
@@ -393,27 +393,27 @@ zstyle ':vcs_info:*+pre-get-data:*' hooks pre-get-data
 setopt promptsubst
 
 precmd_prompt_base() {
-	if [[ -z "${VCSH_REPO_NAME}" ]]; then
-		# colourise user and hostname
-		if [[ "${EUID}" == 0 ]]; then
-			# root is red
-			user_colour="%B%F{red}"
-		else
-			# other users are green
-			user_colour="%F{green}"
-		fi
-		if [[ -z "${SSH_CONNECTION}" ]]; then
-			# local shell is blue
-			host_colour="%B%F{blue}"
-		else
-			# remote connection is yellow
-			host_colour="%B%F{yellow}"
-		fi
-		prompt_base="${user_colour}%n%f%b@${host_colour}%m%f%b"
-		unset host_colour user_colour
-	else
-		prompt_base="%F{yellow}${VCSH_REPO_NAME}%f"
-	fi
+    if [[ -z "${VCSH_REPO_NAME}" ]]; then
+        # colourise user and hostname
+        if [[ "${EUID}" == 0 ]]; then
+            # root is red
+            user_colour="%B%F{red}"
+        else
+            # other users are green
+            user_colour="%F{green}"
+        fi
+        if [[ -z "${SSH_CONNECTION}" ]]; then
+            # local shell is blue
+            host_colour="%B%F{blue}"
+        else
+            # remote connection is yellow
+            host_colour="%B%F{yellow}"
+        fi
+        prompt_base="${user_colour}%n%f%b@${host_colour}%m%f%b"
+        unset host_colour user_colour
+    else
+        prompt_base="%F{yellow}${VCSH_REPO_NAME}%f"
+    fi
 }
 add-zsh-hook precmd precmd_prompt_base
 
@@ -422,47 +422,47 @@ PS1="\${prompt_base}:%B%F{black}%2~%f%b\${vcs_info_msg_0_}%#"
 
 # Prompt on the right side {{{
 function set_RPS1 {
-	# current time, colour depends on the exit status of the last command
-	RPS1_time="%(?.%B%F{yellow}.%B%F{magenta})[%*]%f%b"
-	# display [CMD] when in vicmd mode
-	if [[ "$1" = "vicmd" ]]; then
-		RPS1_mode="%B%F{yellow}[CMD]%f%b"
-	else
-		RPS1_mode=""
-	fi
-	RPS1="${RPS1_mode}${RPS1_time}"
+    # current time, colour depends on the exit status of the last command
+    RPS1_time="%(?.%B%F{yellow}.%B%F{magenta})[%*]%f%b"
+    # display [CMD] when in vicmd mode
+    if [[ "$1" = "vicmd" ]]; then
+        RPS1_mode="%B%F{yellow}[CMD]%f%b"
+    else
+        RPS1_mode=""
+    fi
+    RPS1="${RPS1_mode}${RPS1_time}"
 }
 set_RPS1
 
 function zle-keymap-select {
-	set_RPS1 $KEYMAP
-	zle reset-prompt
+    set_RPS1 $KEYMAP
+    zle reset-prompt
 }
 zle -N zle-keymap-select
 function zle-line-init {
-	# call the terminfo fix from earlier in this file
-	if whence terminfo_zle-line-init &>/dev/null; then
-		terminfo_zle-line-init
-	fi
-	set_RPS1 $KEYMAP
-	zle reset-prompt
+    # call the terminfo fix from earlier in this file
+    if whence terminfo_zle-line-init &>/dev/null; then
+        terminfo_zle-line-init
+    fi
+    set_RPS1 $KEYMAP
+    zle reset-prompt
 }
 zle -N zle-line-init
 # redraw the promp when the line finishes to update the time
 function zle-line-finish {
-	# call the terminfo fix from earlier in this file
-	if whence terminfo_zle-line-finish &>/dev/null; then
-		terminfo_zle-line-finish
-	fi
-	zle reset-prompt
+    # call the terminfo fix from earlier in this file
+    if whence terminfo_zle-line-finish &>/dev/null; then
+        terminfo_zle-line-finish
+    fi
+    zle reset-prompt
 }
 zle -N zle-line-finish
 
 # catch ^C (SIGINT), reset RPS1, and return the signal
 # this is required as pressing ^C in CMD mode displays the wrong prompt in the next line
 #function TRAPINT() {
-#	set_RPS1
-#	return $(( 128 + $1 ))
+#   set_RPS1
+#   return $(( 128 + $1 ))
 #}
 
 # }}}
@@ -471,24 +471,24 @@ zle -N zle-line-finish
 
 # Set the window title {{{
 case $TERM in
-	*xterm*|rxvt*|(dt|k|E)term|gnome*)
-		precmd_title () { print -Pn "\e]0;[%n@%M:%~]\a" }
-		preexec_title () { print -Pn "\e]0;[%n@%M:%~] (\$1)\a" }
-		add-zsh-hook precmd precmd_title
-		add-zsh-hook preexec preexec_title
-	;;
+    *xterm*|rxvt*|(dt|k|E)term|gnome*)
+        precmd_title () { print -Pn "\e]0;[%n@%M:%~]\a" }
+        preexec_title () { print -Pn "\e]0;[%n@%M:%~] (\$1)\a" }
+        add-zsh-hook precmd precmd_title
+        add-zsh-hook preexec preexec_title
+    ;;
     screen|screen-256color)
-		precmd_title () {
-			print -Pn "\e]83;title \"\$1\"\a"
-			print -Pn "\e]0;\$TERM - (%L) [%n@%M:%~]\a"
-		}
-		preexec_title () {
-			print -Pn "\e]83;title \"\$1\"\a"
-			print -Pn "\e]0;\$TERM - (%L) [%n@%M:%~] (\$1)\a"
-		}
-		add-zsh-hook precmd precmd_title
-		add-zsh-hook preexec preexec_title
-	;;
+        precmd_title () {
+            print -Pn "\e]83;title \"\$1\"\a"
+            print -Pn "\e]0;\$TERM - (%L) [%n@%M:%~]\a"
+        }
+        preexec_title () {
+            print -Pn "\e]83;title \"\$1\"\a"
+            print -Pn "\e]0;\$TERM - (%L) [%n@%M:%~] (\$1)\a"
+        }
+        add-zsh-hook precmd precmd_title
+        add-zsh-hook preexec preexec_title
+    ;;
 esac
 
 # }}}
@@ -551,14 +551,14 @@ zstyle ':completion:*:history-words' stop yes
 
 # processes {{{
 if [[ "$EUID" == 0 ]]; then
-	# process completion for root: all processes
-	zstyle ':completion:*:processes'       command 'ps -e -o user,pid,cputime,command'
-	zstyle ':completion:*:processes-names' command 'ps ax -o command | grep -v "^\[.*\]$" |  uniq'
+    # process completion for root: all processes
+    zstyle ':completion:*:processes'       command 'ps -e -o user,pid,cputime,command'
+    zstyle ':completion:*:processes-names' command 'ps ax -o command | grep -v "^\[.*\]$" |  uniq'
 else
-	# process completion of other users: only user processes, unless the
-	# current line starts with 'sudo'
-	zstyle ':completion:*:processes'       command '[[ ${BUFFER:0:4} == 'sudo' ]] && ps -e -o user,pid,cputime,command || ps -au$USER -o pid,cputime,command'
-	zstyle ':completion:*:processes-names' command '[[ ${BUFFER:0:4} == 'sudo' ]] && ps ax -o command | grep -v "^\[.*\]$" | uniq || ps c -u ${USER} -o command | uniq'
+    # process completion of other users: only user processes, unless the
+    # current line starts with 'sudo'
+    zstyle ':completion:*:processes'       command '[[ ${BUFFER:0:4} == 'sudo' ]] && ps -e -o user,pid,cputime,command || ps -au$USER -o pid,cputime,command'
+    zstyle ':completion:*:processes-names' command '[[ ${BUFFER:0:4} == 'sudo' ]] && ps ax -o command | grep -v "^\[.*\]$" | uniq || ps c -u ${USER} -o command | uniq'
 fi
 # always show a list of processes, even if it is only one
 zstyle ':completion:*:*:(kill|killall):*'  force-list always
